---
tags:
  - 初めてのGo言語
---

## エラー処理の基本

Goは関数から `error` 型を戻すことでエラーを処理する。これは単なる慣習だが、誰もが守ることになっているため、破るべきではない。

- 関数が期待通りに実行された場合は `error` には `nil` が返される
- うまくいかない場合はエラーを表す値が返される
- 呼び出し側では `error` の戻り値を `nil` と比較することでチェックし、エラーを処理したり、独自のエラーを返したりする

[errors.New](#errors.New) や [fmt.Errorf](#fmt.Errorf) にエラーを示す文字列を渡して新しいエラーを生成し、それが戻される。大文字で始めたり、句点や改行を置くことはしない。`nil` 以外のエラーを戻す場合、他の戻り値はそれぞれの型のゼロ値にすべき。

例外を持つ言語と違い、Goにはエラーが返されたときにそれを検知する仕組みが存在しないため、if を使って都度エラー用変数が `nil` 以外の値になっていないかチェックする必要がある (`if err != nil {...}`)。

`error` は組み込みのインタフェースで、メソッドを一つだけ定義している。

```go
type error interface {
	Error() string
}
```

このインタフェースを実装するものは `error` であるとみなされる。エラーがないことを示すときに `nil` を返すのは、[`nil` がインタフェース型のゼロ値](Goのインタフェース.md#インタフェースとnil)であるため。

## 文字列からエラーを生成する方法

Goの標準ライブラリは、文字列からエラーを生成する方法を2つ提供している。

### errors.New

関数 [[errors.New]] は文字列 (`string`) を受け取り、`error` を返す。

呼び出し側で [[fmt.Println]] に `error` を渡すと、メソッド `Error` を自動的に呼び出し、`errors.New` で受け取った文字列が返される。

### fmt.Errorf

関数 [[fmt.Errorf]] はエラー生成時に [[fmt.Printf]] のすべてのフォーマット関連の[[動詞]] (verb) を使うことができる。

[errors.New](#errors.New) と同様、戻されたエラーのインスタンスに対してメソッド `Error` を呼び出すと、文字列が返される。

```go
fmt.Errorf("%dは偶数ではありません", i)
```

